# Generated by Django 4.1.3 on 2022-11-24 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='registeredUser',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('mailing_address', models.TextField(default='Default Address')),
                ('billing_address', models.TextField(default='Default Address')),
                ('pref_payment_method', models.CharField(max_length=20)),
                ('cc_num', models.IntegerField(default=1111111111111111)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=1)),
                ('dates', models.ManyToManyField(blank=True, to='booking.date')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no data', max_length=15)),
                ('party_size', models.IntegerField(default=1)),
                ('email', models.EmailField(default='customer_default@gmail.com', max_length=254)),
                ('reservation_phone', models.CharField(max_length=10, null=True)),
                ('dates', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.date')),
                ('tables', models.ManyToManyField(to='booking.table')),
            ],
        ),
    ]
